class Qcm < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_and_belongs_to_many :questions

  def toTxt()
    texte = "#AMC-TXT auto-generated by FATAL_BACKEND for QCM #{id}\n"
    texte += "Font: Linux Libertine O\n"
    texte += "PaperSize: A4\n"
    texte += "Lang: FR\n"
    texte += "Title :#{titre}\n\n\n"
    texte += "Presentation: #{entete}\n\n"

    questions.each do |question|
      texte+= question.toTxt() + "\n"
    end
    texte
  end
end
